### PR TITLE
Add rosbuild support in GenerateRTTRosCommPackage and rtt_ros service

### PR DESCRIPTION
**Pull request by meyerj**
This is a follow-up of #9. Not all goals mentioned there have been achieved yet, especially these two points:

>  rosbuild packages can find_package(rtt_roscomm) and call ros_generate_rtt_typekit() and ros_generate_rtt_service_proxies() on rosbuild message packages. This replaces the former rosbuild_include(rtt_rosnode GenerateRTTtypekit) call.
> 
>  The rtt_ros service should be able to import rosbuild packages.

### CODE REVIEW

**Comment by jbohren** [comment]
Looks good!

**Comment by meyerj** [comment]
There is still some more work to do here, especially the rosbuild support in the rtt_ros service.  I just wanted to collect all patches here. I could look into it next week.

**Comment by jbohren** [comment]
Yeah, though I haven't tested it yet, I think since the rtt_ros service uses the rospack C++ API, as long as the manifest.xml files have similar `<export><rtt_ros><plugin_depend>` tags, it will work exactly the same way. I'm going to respond to all of the other comments from Ruben and Peter over the next couple of hours.

**Comment by jbohren** [comment]
We should probably re-vist the naming/design of those export tags too, since that's still open: #3

**Pull request merged**
