### PR TITLE
rtt_ros CFG_EXTRAS as macro + automatic call

### PR DESCRIPTION
**Pull request by jbohren**

### CODE REVIEW

**Comment by meyerj** [comment]
Could you explain shortly why this is needed? For me for example

```
orocos_use_package(orocos-rtt-corba)
```

works fine. If the `use_orocos()` macro is already executed in `rtt_ros-extras.cmake`, what are the use cases for users to call it again?

**Comment by jbohren** [comment]
> Could you explain shortly why this is needed? For me for example
> 
> ```
> orocos_use_package(orocos-rtt-corba)
> ```
> 
> works fine. If the use_orocos() macro is already executed in rtt_ros-extras.cmake, what are the use cases for users to call it again?

Calling `orocos_use_package(rtt-transport-corba)` won't actually do the same thing as calling `find_package(OROCOS-RTT COMPONENTS rtt-transport-corba)` since `rtt-transport-corba` isn't a full-fledged orocos package, it's just a component of the RTT package.

**Comment by meyerj** [comment]
Is it okay to include the `UseOROCOS-RTT.cmake` within the macro and have it called multiple times if `use_orocos()` is called for additional components?

**Comment by jbohren** [comment]
> Is it okay to include the UseOROCOS-RTT.cmake within the macro and have it called multiple times if use_orocos() is called for additional components?

Yes, it handles that case without destroying things the same way catkin does.

**Comment by meyerj** [comment]
I added a package to test rtt_ros_integration with rosbuild packages. See #45.

With the small patch from bfc57cec43acf10dbc0e64b4be4ca8d98aac2a0f, this one can be merged. Probably it should be rebased first as their have been some updates on hydro-devel since the pull request has been created.

**Pull request merged**
